name: UPnP
version: 2.1
main: xyz.necrozma.upnp.Main
api-version: "1.20"
author: necrozma
website: necrozma.xyz
description: A Plugin to open UPNP ports for your Minecraft server

commands:
  upnpverbose:
    description: Toggle or check UPnP verbose troubleshooting logs
    usage: /upnpverbose <on|off|toggle|status>
    aliases: [upnpvlog]
    permission: upnp.troubleshoot
    permission-message: You do not have permission to use this command.

permissions:
  upnp.troubleshoot:
    description: Allows toggling UPnP troubleshooting verbose logs
    default: op
